"""Shared query corpus for the engine A/B audit — pure data, no slayer imports.

Entries: {id, family, query: dict | list[dict], variables?, expect_error,
expect_error_match?, ordered, subset_100k?, oracle?: {fn, args}}.
The same corpus runs against the pinned PyPI engine and the branch engine.
"""

DS = "bench"

# ---------------------------------------------------------------------------
# Model definitions (dicts consumed by both engine versions)
# ---------------------------------------------------------------------------

MODELS = [
    {
        "name": "orders",
        "sql_table": "orders",
        "data_source": DS,
        "default_time_dimension": "created_at",
        "columns": [
            {"name": "id", "sql": "id", "type": "INT", "primary_key": True},
            {"name": "customer_id", "sql": "customer_id", "type": "INT"},
            {"name": "shop_id", "sql": "shop_id", "type": "INT"},
            {"name": "category", "sql": "category", "type": "TEXT"},
            {"name": "created_at", "sql": "created_at", "type": "TIMESTAMP"},
            {"name": "completed_at", "sql": "completed_at", "type": "TIMESTAMP"},
            {"name": "cancelled_at", "sql": "cancelled_at", "type": "TIMESTAMP"},
            {"name": "total_cost", "sql": "cost", "type": "DOUBLE"},
            {"name": "latest_cost", "sql": "cost", "type": "DOUBLE"},
        ],
        "measures": [
            {"name": "order_count", "formula": "*:count"},
            {"name": "revenue", "formula": "total_cost:sum"},
        ],
        "joins": [
            {"target_model": "customers", "join_pairs": [["customer_id", "id"]]},
            {"target_model": "shops", "join_pairs": [["shop_id", "id"]]},
        ],
    },
    {
        "name": "customers",
        "sql_table": "customers",
        "data_source": DS,
        "columns": [
            {"name": "id", "sql": "id", "type": "INT", "primary_key": True},
            {"name": "name", "sql": "name", "type": "TEXT"},
            {"name": "segment", "sql": "segment", "type": "TEXT"},
            {"name": "primary_shop_id", "sql": "primary_shop_id", "type": "INT"},
        ],
    },
    {
        "name": "shops",
        "sql_table": "shops",
        "data_source": DS,
        "columns": [
            {"name": "id", "sql": "id", "type": "INT", "primary_key": True},
            {"name": "name", "sql": "name", "type": "TEXT"},
            {"name": "region_id", "sql": "region_id", "type": "INT"},
            {"name": "avg_cost", "sql": "avg_cost", "type": "DOUBLE"},
            {"name": "size", "sql": "size", "type": "INT"},
        ],
        "joins": [
            {"target_model": "regions", "join_pairs": [["region_id", "id"]]},
        ],
    },
    {
        "name": "regions",
        "sql_table": "regions",
        "data_source": DS,
        "columns": [
            {"name": "id", "sql": "id", "type": "INT", "primary_key": True},
            {"name": "name", "sql": "name", "type": "TEXT"},
        ],
    },
]

# ---------------------------------------------------------------------------
# Adversarial dataset: null/unmatched join keys, duplicate dimension PK,
# null/zero/negative measures, a gap month (2024-03), in-month cost ties.
# Category sums are pairwise distinct so ORDER BY sum is tie-free.
# ---------------------------------------------------------------------------

def _order(oid, cust, shop, category, cost, created, completed=None, cancelled=None):
    return {
        "id": oid, "customer_id": cust, "shop_id": shop, "category": category,
        "cost": cost, "created_at": created,
        "completed_at": completed, "cancelled_at": cancelled,
    }


ADVERSARIAL_TABLES = {
    "regions": [
        {"id": 1, "name": "North America"},
        {"id": 2, "name": "Europe"},
        {"id": 3, "name": "Asia Pacific"},
    ],
    "shops": [
        {"id": 1, "name": "Alpha Market", "region_id": 1, "avg_cost": 1000, "avg_frequency": 100, "size": 50},
        {"id": 2, "name": "Beta Store", "region_id": 2, "avg_cost": 2000, "avg_frequency": 80, "size": 70},
        {"id": 3, "name": "Gamma Hub", "region_id": None, "avg_cost": 1500, "avg_frequency": 90, "size": 40},
        {"id": 4, "name": "Delta Depot", "region_id": 99, "avg_cost": 3000, "avg_frequency": 60, "size": 90},
    ],
    "customers": [
        {"id": 1, "name": "Ann Smith", "segment": "average", "primary_shop_id": 1},
        {"id": 2, "name": "Bob Jones", "segment": "whale", "primary_shop_id": 1},
        {"id": 2, "name": "Bobby Jones", "segment": "poor", "primary_shop_id": 2},
        {"id": 3, "name": "Cid Lee", "segment": "upper", "primary_shop_id": 3},
        {"id": 4, "name": "Dee Kim", "segment": "average", "primary_shop_id": 4},
    ],
    "orders": [
        _order(1, 1, 1, "electronics", 5000, "2024-01-05 10:00:00", "2024-01-06 10:00:00"),
        _order(2, 1, 1, "electronics", 5000, "2024-01-31 23:59:59"),
        _order(3, 2, 1, "clothing", 3000, "2024-01-10 09:30:00", "2024-01-11 09:30:00"),
        _order(4, 2, 2, "food", 1500, "2024-01-20 14:00:00", None, "2024-01-21 08:00:00"),
        _order(5, 3, 2, "home", None, "2024-01-25 16:45:00"),
        _order(6, 999, 3, "sports", 2500, "2024-01-28 11:00:00", "2024-01-29 11:00:00"),
        _order(7, None, 3, "food", 1200, "2024-02-02 00:00:00"),
        _order(8, 1, 4, "clothing", 0, "2024-02-05 12:00:00", "2024-02-06 12:00:00"),
        _order(9, 2, 4, "electronics", -500, "2024-02-08 13:15:00"),
        _order(10, 3, 1, "home", 4200, "2024-02-11 10:30:00", "2024-02-12 10:30:00"),
        _order(11, 4, 1, "sports", 3300, "2024-02-14 15:00:00"),
        _order(12, 1, 2, "food", 1800, "2024-02-17 17:20:00", "2024-02-18 17:20:00"),
        _order(13, 2, 2, "clothing", 2000, "2024-02-20 09:00:00", None, "2024-02-22 09:00:00"),
        _order(14, 3, 3, "electronics", 7500, "2024-02-23 18:00:00", "2024-02-24 18:00:00"),
        _order(15, 4, 3, "home", None, "2024-02-26 19:30:00"),
        _order(16, 1, 4, "sports", 2500, "2024-04-01 08:00:00", "2024-04-02 08:00:00"),
        _order(17, 2, 4, "food", 900, "2024-04-04 10:10:00"),
        _order(18, 3, 1, "clothing", 4700, "2024-04-07 11:11:00", "2024-04-08 11:11:00"),
        _order(19, 4, 1, "electronics", 5100, "2024-04-10 12:12:00"),
        _order(20, None, 2, "home", 600, "2024-04-13 13:13:00", "2024-04-14 13:13:00"),
        _order(21, 1, 2, "sports", 1000, "2024-04-16 14:14:00"),
        _order(22, 2, 3, "food", 2200, "2024-04-19 15:15:00", "2024-04-20 15:15:00"),
        _order(23, 3, 3, "clothing", 800, "2024-04-22 16:16:00"),
        _order(24, 4, 4, "home", 3900, "2024-04-25 17:17:00", "2024-04-26 17:17:00"),
        _order(25, 1, 4, "electronics", 6100, "2024-05-01 09:09:00"),
        _order(26, 2, 1, "food", 1400, "2024-05-04 10:00:00", "2024-05-05 10:00:00"),
        _order(27, 3, 1, "sports", 4400, "2024-05-07 11:00:00", None, "2024-05-09 11:00:00"),
        _order(28, 4, 2, "clothing", 2600, "2024-05-10 12:00:00", "2024-05-11 12:00:00"),
        _order(29, 1, 2, "home", 1700, "2024-05-13 13:00:00"),
        _order(30, 77, 3, "food", 2100, "2024-05-16 14:00:00", "2024-05-17 14:00:00"),
    ],
}

# ---------------------------------------------------------------------------
# Query corpus
# ---------------------------------------------------------------------------

MONTH_TD = [{"dimension": "created_at", "granularity": "month"}]
WEEK_TD = [{"dimension": "created_at", "granularity": "week"}]
ASC_TIME = [{"column": "created_at", "direction": "asc"}]


def _entry(entry_id, family, query, *, ordered=False, expect_error=False, **extra):
    return {
        "id": entry_id, "family": family, "query": query,
        "ordered": ordered, "expect_error": expect_error, **extra,
    }


def _q(**kwargs):
    return {"source_model": "orders", **kwargs}


def _month_oracle(aggs, post=None, **extra):
    args = {
        "table": "orders",
        "time_bucket": {"col": "created_at", "gran": "month"},
        "groupby": ["created_at_month"],
        "aggs": aggs,
        "order_by": [["created_at_month", "asc"]],
        **extra,
    }
    if post:
        args["post"] = post
    return {"fn": "agg", "args": args}


SUM_COST = {"col": "cost", "op": "sum"}
COUNT_STAR = {"op": "count_star"}

ENTRIES = [
    # ---- bench: the 15 pre-existing benchmark queries -----------------------
    _entry("bench_simple_count", "bench",
           _q(measures=["*:count"]),
           oracle={"fn": "agg", "args": {"aggs": [COUNT_STAR]}},
           subset_100k=True),
    _entry("bench_count_by_category", "bench",
           _q(measures=["*:count", "total_cost:sum"], dimensions=["category"]),
           oracle={"fn": "agg", "args": {"groupby": ["category"], "aggs": [COUNT_STAR, SUM_COST]}},
           subset_100k=True),
    _entry("bench_monthly_revenue", "bench",
           _q(measures=["total_cost:sum"], time_dimensions=MONTH_TD, order=ASC_TIME),
           ordered=True, oracle=_month_oracle([SUM_COST]), subset_100k=True),
    _entry("bench_monthly_cumsum", "bench",
           _q(measures=["total_cost:sum", {"formula": "cumsum(total_cost:sum)", "name": "running"}],
              time_dimensions=MONTH_TD, order=ASC_TIME),
           ordered=True,
           oracle=_month_oracle([SUM_COST], post=[{"op": "cumsum", "on": "cost_sum"}]),
           subset_100k=True),
    _entry("bench_monthly_change", "bench",
           _q(measures=["total_cost:sum", {"formula": "change(total_cost:sum)", "name": "chg"}],
              time_dimensions=MONTH_TD, order=ASC_TIME),
           ordered=True,
           oracle=_month_oracle([SUM_COST], post=[{"op": "change", "on": "cost_sum"}])),
    _entry("bench_monthly_change_pct", "bench",
           _q(measures=["total_cost:sum", {"formula": "change_pct(total_cost:sum)", "name": "pct"}],
              time_dimensions=MONTH_TD, order=ASC_TIME),
           ordered=True),
    _entry("bench_monthly_time_shift", "bench",
           _q(measures=["total_cost:sum",
                        {"formula": "time_shift(total_cost:sum, -1, 'month')", "name": "prev"}],
              time_dimensions=MONTH_TD, order=ASC_TIME),
           ordered=True),
    _entry("bench_monthly_yoy", "bench",
           _q(measures=["total_cost:sum",
                        {"formula": "time_shift(total_cost:sum, -1, 'year')", "name": "yoy"}],
              time_dimensions=MONTH_TD, order=ASC_TIME),
           ordered=True, subset_100k=True),
    _entry("bench_rank_by_category", "bench",
           _q(measures=["total_cost:sum", {"formula": "rank(total_cost:sum)", "name": "rnk"}],
              dimensions=["category"],
              order=[{"column": "total_cost_sum", "direction": "desc"}]),
           ordered=True),
    _entry("bench_last_function", "bench",
           _q(measures=["total_cost:sum", {"formula": "last(total_cost:sum)", "name": "latest"}],
              time_dimensions=MONTH_TD, order=ASC_TIME),
           ordered=True),
    _entry("bench_last_agg_type", "bench",
           _q(measures=["total_cost:sum", "latest_cost:last"],
              time_dimensions=MONTH_TD, order=ASC_TIME),
           ordered=True),
    _entry("bench_filtered_with_transform", "bench",
           _q(measures=["total_cost:sum"], time_dimensions=MONTH_TD,
              filters=["change(total_cost:sum) > 0"], order=ASC_TIME),
           ordered=True),
    _entry("bench_time_shift_date_range", "bench",
           _q(measures=["total_cost:sum",
                        {"formula": "time_shift(total_cost:sum, -1, 'month')", "name": "prev"}],
              time_dimensions=[{"dimension": "created_at", "granularity": "month",
                                "date_range": ["2024-06-01", "2024-12-31"]}],
              order=ASC_TIME),
           ordered=True),
    _entry("bench_nested_cumsum_change", "bench",
           _q(measures=["total_cost:sum",
                        {"formula": "cumsum(change(total_cost:sum))", "name": "cumchg"}],
              time_dimensions=MONTH_TD, order=ASC_TIME),
           ordered=True),
    _entry("bench_weekly_lag_lead", "bench",
           _q(measures=["*:count", {"formula": "lag(*:count, 1)", "name": "prev_week"},
                        {"formula": "lead(*:count, 1)", "name": "next_week"}],
              time_dimensions=WEEK_TD, order=ASC_TIME),
           ordered=True, subset_100k=True),
    _entry("bench_having_filter", "bench",
           _q(measures=["*:count", "total_cost:sum"], dimensions=["category"],
              filters=["_count > 10"]),
           oracle={"fn": "agg", "args": {"groupby": ["category"],
                                         "aggs": [COUNT_STAR, SUM_COST],
                                         "having": "_count > 10"}}),

    # ---- aggregation sweep --------------------------------------------------
    _entry("agg_sum_avg_min_max", "aggs",
           _q(measures=["total_cost:sum", "total_cost:avg", "total_cost:min", "total_cost:max"]),
           oracle={"fn": "agg", "args": {"aggs": [
               SUM_COST, {"col": "cost", "op": "avg"},
               {"col": "cost", "op": "min"}, {"col": "cost", "op": "max"}]}}),
    _entry("agg_count_star_vs_count", "aggs",
           _q(measures=["*:count", "total_cost:count"]),
           oracle={"fn": "agg", "args": {"aggs": [COUNT_STAR, {"col": "cost", "op": "count"}]}}),
    _entry("agg_count_distinct", "aggs",
           _q(measures=["customer_id:count_distinct"]),
           oracle={"fn": "agg", "args": {"aggs": [{"col": "customer_id", "op": "count_distinct"}]}}),
    _entry("agg_count_distinct_by_cat", "aggs",
           _q(measures=["customer_id:count_distinct"], dimensions=["category"]),
           oracle={"fn": "agg", "args": {"groupby": ["category"],
                                         "aggs": [{"col": "customer_id", "op": "count_distinct"}]}}),
    _entry("agg_last_by_category", "aggs",
           _q(measures=["latest_cost:last"], dimensions=["category"])),
    _entry("agg_first_by_category", "aggs",
           _q(measures=["latest_cost:first"], dimensions=["category"])),
    _entry("agg_median", "aggs", _q(measures=["total_cost:median"])),
    _entry("agg_percentile_50", "aggs", _q(measures=["total_cost:percentile(p=0.5)"])),
    _entry("agg_percentile_90", "aggs", _q(measures=["total_cost:percentile(p=0.9)"])),
    _entry("agg_stddev", "aggs", _q(measures=["total_cost:stddev_samp"])),
    _entry("agg_grouped_multi", "aggs",
           _q(measures=["total_cost:sum", "total_cost:avg"], dimensions=["category"]),
           oracle={"fn": "agg", "args": {"groupby": ["category"],
                                         "aggs": [SUM_COST, {"col": "cost", "op": "avg"}]}}),

    # ---- joins --------------------------------------------------------------
    _entry("join_dim_segment", "joins",
           _q(measures=["total_cost:sum"], dimensions=["customers.segment"]),
           oracle={"fn": "agg", "args": {
               "joins": [{"table": "customers", "left_on": "customer_id", "right_on": "id"}],
               "groupby": ["customers.segment"], "aggs": [SUM_COST]}},
           subset_100k=True),
    _entry("join_two_hop_region", "joins",
           _q(measures=["*:count"], dimensions=["shops.regions.name"]),
           oracle={"fn": "agg", "args": {
               "joins": [{"table": "shops", "left_on": "shop_id", "right_on": "id"},
                         {"table": "regions", "left_on": "shops.region_id", "right_on": "id"}],
               "groupby": ["regions.name"], "aggs": [COUNT_STAR]}},
           subset_100k=True),
    _entry("join_filter_on_joined", "joins",
           _q(measures=["total_cost:sum"], dimensions=["category"],
              filters=["customers.segment = 'whale'"]),
           oracle={"fn": "agg", "args": {
               "joins": [{"table": "customers", "left_on": "customer_id", "right_on": "id"}],
               "filter": "`customers.segment` == 'whale'",
               "groupby": ["category"], "aggs": [SUM_COST]}}),
    _entry("join_order_by_joined_dim", "joins",
           _q(measures=["*:count"], dimensions=["customers.segment"],
              order=[{"column": "customers.segment", "direction": "asc"}]),
           ordered=True),
    _entry("join_measure_on_joined_col", "joins",
           # no oracle: SLayer aggregates cross-model measures over the TARGET
           # model's rows (fan-out protection), not the joined fact rowset
           _q(measures=["shops.size:sum"], dimensions=["category"])),
    _entry("join_cardinality_base", "joins",
           _q(measures=["*:count"], dimensions=["customers.segment"]),
           oracle={"fn": "agg", "args": {
               "joins": [{"table": "customers", "left_on": "customer_id", "right_on": "id"}],
               "groupby": ["customers.segment"], "aggs": [COUNT_STAR]}}),
    _entry("join_cardinality_plus_measure", "joins",
           _q(measures=["*:count", "total_cost:sum"], dimensions=["customers.segment"]),
           oracle={"fn": "agg", "args": {
               "joins": [{"table": "customers", "left_on": "customer_id", "right_on": "id"}],
               "groupby": ["customers.segment"], "aggs": [COUNT_STAR, SUM_COST]}}),
    _entry("join_dims_only_distinct", "joins",
           _q(dimensions=["customers.segment"]),
           oracle={"fn": "agg", "args": {
               "joins": [{"table": "customers", "left_on": "customer_id", "right_on": "id"}],
               "groupby": ["customers.segment"], "aggs": []}}),
    _entry("join_two_hop_filter", "joins",
           _q(measures=["*:count"], filters=["shops.regions.name = 'Europe'"]),
           oracle={"fn": "agg", "args": {
               "joins": [{"table": "shops", "left_on": "shop_id", "right_on": "id"},
                         {"table": "regions", "left_on": "shops.region_id", "right_on": "id"}],
               "filter": "`regions.name` == 'Europe'", "aggs": [COUNT_STAR]}}),
    _entry("join_segment_time", "joins",
           _q(measures=["total_cost:sum"], dimensions=["customers.segment"],
              time_dimensions=MONTH_TD, order=ASC_TIME)),

    # ---- filters ------------------------------------------------------------
    _entry("filter_numeric_gt", "filters",
           _q(measures=["*:count"], filters=["total_cost > 5000"]),
           oracle={"fn": "agg", "args": {"filter": "cost > 5000", "aggs": [COUNT_STAR]}}),
    _entry("filter_range_and", "filters",
           _q(measures=["total_cost:sum"], filters=["total_cost >= 1000 and total_cost <= 8000"]),
           oracle={"fn": "agg", "args": {"filter": "cost >= 1000 and cost <= 8000",
                                         "aggs": [SUM_COST]}}),
    _entry("filter_neq", "filters",
           _q(measures=["*:count"], dimensions=["category"], filters=["category <> 'food'"]),
           oracle={"fn": "agg", "args": {"filter": "category != 'food'",
                                         "groupby": ["category"], "aggs": [COUNT_STAR]}}),
    _entry("filter_in_list", "filters",
           _q(measures=["total_cost:sum"], filters=["category in ('food', 'electronics')"]),
           oracle={"fn": "agg", "args": {"filter": "category in ['food', 'electronics']",
                                         "aggs": [SUM_COST]}},
           subset_100k=True),
    _entry("filter_not_in", "filters",
           _q(measures=["*:count"], filters=["category not in ('sports', 'home')"]),
           oracle={"fn": "agg", "args": {"filter": "category not in ['sports', 'home']",
                                         "aggs": [COUNT_STAR]}}),
    _entry("filter_is_null", "filters",
           _q(measures=["*:count"], filters=["cancelled_at IS NULL"]),
           oracle={"fn": "agg", "args": {"filter": "cancelled_at.isnull()", "aggs": [COUNT_STAR]}}),
    _entry("filter_is_not_null", "filters",
           _q(measures=["*:count"], filters=["completed_at IS NOT NULL"]),
           oracle={"fn": "agg", "args": {"filter": "completed_at.notnull()", "aggs": [COUNT_STAR]}}),
    _entry("filter_like", "filters",
           _q(measures=["*:count"], filters=["category like 'c%'"]),
           oracle={"fn": "agg", "args": {"filter": "category.str.startswith('c')",
                                         "aggs": [COUNT_STAR]}}),
    _entry("filter_bool_literal", "filters",
           # `false` in any casing: rejected by 0.9.12, accepted post-#316
           _q(measures=["*:count"], filters=["category = 'food' or false"]),
           oracle={"fn": "agg", "args": {"filter": "category == 'food'", "aggs": [COUNT_STAR]}}),
    _entry("filter_having_measure", "filters",
           _q(measures=["*:count"], dimensions=["category"], filters=["_count > 3"]),
           oracle={"fn": "agg", "args": {"groupby": ["category"], "aggs": [COUNT_STAR],
                                         "having": "_count > 3"}},
           subset_100k=True),
    _entry("filter_where_and_having", "filters",
           _q(measures=["*:count"], dimensions=["category"],
              filters=["total_cost > 1000", "_count > 2"]),
           oracle={"fn": "agg", "args": {"filter": "cost > 1000", "groupby": ["category"],
                                         "aggs": [COUNT_STAR], "having": "_count > 2"}}),
    _entry("filter_rank_transform", "filters",
           _q(measures=["total_cost:sum"], dimensions=["category"],
              filters=["rank(total_cost:sum) <= 3"],
              order=[{"column": "total_cost_sum", "direction": "desc"}]),
           ordered=True),
    _entry("filter_date_range", "filters",
           _q(measures=["total_cost:sum"],
              time_dimensions=[{"dimension": "created_at", "granularity": "month",
                                "date_range": ["2024-01-01", "2024-06-30"]}],
              order=ASC_TIME),
           ordered=True),
    _entry("var_scalar_number", "filters",
           _q(measures=["*:count"], filters=["total_cost > {min_cost}"]),
           variables={"min_cost": 2000},
           oracle={"fn": "agg", "args": {"filter": "cost > 2000", "aggs": [COUNT_STAR]}}),
    _entry("var_scalar_string", "filters",
           _q(measures=["*:count"], filters=["category = '{cat}'"]),
           variables={"cat": "food"},
           oracle={"fn": "agg", "args": {"filter": "category == 'food'", "aggs": [COUNT_STAR]}}),
    _entry("var_list_in", "filters",
           _q(measures=["total_cost:sum"], filters=["category in ({cats})"]),
           variables={"cats": ["food", "clothing"]},
           oracle={"fn": "agg", "args": {"filter": "category in ['food', 'clothing']",
                                         "aggs": [SUM_COST]}}),
    _entry("var_list_empty", "filters",
           _q(measures=["*:count"], filters=["category in ({cats})"]),
           variables={"cats": []}, expect_error=True),
    _entry("var_missing", "filters",
           _q(measures=["*:count"], filters=["category = '{undefined_var}'"]),
           expect_error=True, expect_error_match="undefined_var"),

    # ---- formulas -----------------------------------------------------------
    _entry("formula_ratio", "formulas",
           _q(measures=[{"formula": "total_cost:sum / *:count", "name": "aov"}],
              dimensions=["category"]),
           subset_100k=True),
    _entry("formula_spread", "formulas",
           _q(measures=[{"formula": "total_cost:max - total_cost:min", "name": "spread"}])),
    _entry("formula_saved_measure_ref", "formulas",
           # DEV-1779 shape: a formula referencing model-saved measures
           _q(measures=[{"formula": "revenue / order_count", "name": "aov_saved"}],
              dimensions=["category"])),
    _entry("formula_saved_measure_direct", "formulas",
           _q(measures=[{"formula": "revenue", "name": "rev"}], dimensions=["category"]),
           oracle={"fn": "agg", "args": {"groupby": ["category"], "aggs": [SUM_COST]}}),
    _entry("formula_adhoc_sibling_ref", "formulas",
           # ad-hoc query measures cannot reference each other by name (both sides reject)
           _q(measures=[{"formula": "total_cost:sum", "name": "rev"},
                        {"formula": "rev / 100", "name": "rev_dollars"}],
              dimensions=["category"]),
           expect_error=True),
    _entry("formula_label", "formulas",
           _q(measures=[{"formula": "total_cost:sum / *:count", "name": "aov",
                         "label": "Average Order Value"}],
              dimensions=[{"name": "category", "label": "Category"}])),
    _entry("formula_arith_time_shift", "formulas",
           _q(measures=["total_cost:sum",
                        {"formula": "total_cost:sum - time_shift(total_cost:sum, -1, 'month')",
                         "name": "mom_diff"}],
              time_dimensions=MONTH_TD, order=ASC_TIME),
           ordered=True),
    _entry("formula_scalar_round", "formulas",
           _q(measures=[{"formula": "round(total_cost:avg)", "name": "avg_rounded"}],
              dimensions=["category"])),
    _entry("formula_scalar_filter", "formulas",
           _q(measures=["*:count"], filters=["lower(category) = 'food'"]),
           oracle={"fn": "agg", "args": {"filter": "category == 'food'", "aggs": [COUNT_STAR]}}),
    _entry("formula_coalesce_filter", "formulas",
           _q(measures=["*:count"], filters=["coalesce(cancelled_at, completed_at) IS NULL"]),
           oracle={"fn": "agg", "args": {
               "filter": "cancelled_at.isnull() and completed_at.isnull()",
               "aggs": [COUNT_STAR]}}),
    _entry("formula_order_by_named", "formulas",
           _q(measures=[{"formula": "total_cost:sum", "name": "rev"}], dimensions=["category"],
              order=[{"column": "rev", "direction": "desc"}]),
           ordered=True),

    # ---- time granularities -------------------------------------------------
    _entry("time_day", "time",
           _q(measures=["*:count"],
              time_dimensions=[{"dimension": "created_at", "granularity": "day",
                                "date_range": ["2024-01-01", "2024-01-31"]}],
              order=ASC_TIME),
           ordered=True),
    _entry("time_week", "time",
           _q(measures=["total_cost:sum"], time_dimensions=WEEK_TD, order=ASC_TIME),
           ordered=True),
    _entry("time_week_sunday", "time",
           _q(measures=["total_cost:sum"],
              time_dimensions=[{"dimension": "created_at", "granularity": "week_sunday"}],
              order=ASC_TIME),
           ordered=True),
    _entry("time_quarter", "time",
           _q(measures=["total_cost:sum"],
              time_dimensions=[{"dimension": "created_at", "granularity": "quarter"}],
              order=ASC_TIME),
           ordered=True),
    _entry("time_year", "time",
           _q(measures=["total_cost:sum"],
              time_dimensions=[{"dimension": "created_at", "granularity": "year"}],
              order=ASC_TIME),
           ordered=True,
           oracle={"fn": "agg", "args": {
               "table": "orders",
               "time_bucket": {"col": "created_at", "gran": "year"},
               "groupby": ["created_at_year"], "aggs": [SUM_COST],
               "order_by": [["created_at_year", "asc"]]}}),
    _entry("time_shift_quarter", "time",
           _q(measures=["total_cost:sum",
                        {"formula": "time_shift(total_cost:sum, -1, 'quarter')", "name": "prev_q"}],
              time_dimensions=[{"dimension": "created_at", "granularity": "quarter"}],
              order=ASC_TIME),
           ordered=True),
    _entry("time_whole_periods", "time",
           _q(measures=["total_cost:sum"], time_dimensions=MONTH_TD,
              whole_periods_only=True, order=ASC_TIME),
           ordered=True),
    _entry("time_no_order", "time",
           _q(measures=["total_cost:sum"], time_dimensions=MONTH_TD),
           oracle=_month_oracle([SUM_COST])),

    # ---- order / limit / offset ---------------------------------------------
    _entry("order_limit_top3", "order_limit",
           _q(measures=["total_cost:sum"], dimensions=["category"],
              order=[{"column": "total_cost_sum", "direction": "desc"}], limit=3),
           ordered=True,
           oracle={"fn": "agg", "args": {"groupby": ["category"], "aggs": [SUM_COST],
                                         "order_by": [["cost_sum", "desc"]], "limit": 3}},
           subset_100k=True),
    _entry("order_limit_offset", "order_limit",
           _q(measures=["total_cost:sum"], dimensions=["category"],
              order=[{"column": "total_cost_sum", "direction": "desc"}], limit=2, offset=1),
           ordered=True,
           oracle={"fn": "agg", "args": {"groupby": ["category"], "aggs": [SUM_COST],
                                         "order_by": [["cost_sum", "desc"]],
                                         "limit": 2, "offset": 1}}),
    _entry("order_by_dim_asc", "order_limit",
           _q(measures=["*:count"], dimensions=["category"],
              order=[{"column": "category", "direction": "asc"}]),
           ordered=True,
           oracle={"fn": "agg", "args": {"groupby": ["category"], "aggs": [COUNT_STAR],
                                         "order_by": [["category", "asc"]]}}),
    _entry("order_unprojected_flat", "order_limit",
           _q(dimensions=["id"], distinct_dimension_values=False,
              order=[{"column": "total_cost", "direction": "desc"},
                     {"column": "id", "direction": "asc"}],
              limit=5),
           ordered=True),
    _entry("order_two_dims", "order_limit",
           _q(measures=["*:count"], dimensions=["category", "customers.segment"],
              order=[{"column": "category", "direction": "asc"},
                     {"column": "customers.segment", "direction": "desc"}]),
           ordered=True),

    # ---- multi dim/measure cardinality --------------------------------------
    _entry("multi_2dim_2meas", "multi",
           _q(measures=["total_cost:sum", "*:count"],
              dimensions=["category", "customers.segment"]),
           oracle={"fn": "agg", "args": {
               "joins": [{"table": "customers", "left_on": "customer_id", "right_on": "id"}],
               "groupby": ["category", "customers.segment"],
               "aggs": [SUM_COST, COUNT_STAR]}}),
    _entry("multi_3meas_time", "multi",
           _q(measures=["total_cost:sum", "total_cost:avg", "*:count"],
              time_dimensions=MONTH_TD, order=ASC_TIME),
           ordered=True,
           oracle=_month_oracle([SUM_COST, {"col": "cost", "op": "avg"}, COUNT_STAR])),
    _entry("multi_dim_time_mix", "multi",
           _q(measures=["total_cost:sum"], dimensions=["category"],
              time_dimensions=MONTH_TD, order=ASC_TIME)),
    _entry("multi_wide", "multi",
           _q(measures=["total_cost:sum", "total_cost:avg", "total_cost:min",
                        "total_cost:max", "*:count", "customer_id:count_distinct"],
              dimensions=["category"]),
           oracle={"fn": "agg", "args": {"groupby": ["category"], "aggs": [
               SUM_COST, {"col": "cost", "op": "avg"}, {"col": "cost", "op": "min"},
               {"col": "cost", "op": "max"}, COUNT_STAR,
               {"col": "customer_id", "op": "count_distinct"}]}},
           subset_100k=True),
    _entry("multi_dims_only", "multi",
           _q(dimensions=["category", "customers.segment"]),
           oracle={"fn": "agg", "args": {
               "joins": [{"table": "customers", "left_on": "customer_id", "right_on": "id"}],
               "groupby": ["category", "customers.segment"], "aggs": []}}),

    # ---- multi-stage query lists --------------------------------------------
    _entry("ms_chain_count", "multi_stage",
           [
               {"name": "monthly", "source_model": "orders",
                "measures": ["*:count", "total_cost:sum"], "time_dimensions": MONTH_TD},
               {"source_model": "monthly", "measures": ["*:count"]},
           ],
           oracle={"fn": "agg", "args": {
               "time_bucket": {"col": "created_at", "gran": "month"},
               "aggs": [{"col": "created_at_month", "op": "count_distinct"}]}}),
    _entry("ms_chain_agg_over_agg", "multi_stage",
           [
               {"name": "cat_rev", "source_model": "orders", "dimensions": ["category"],
                "measures": [{"formula": "total_cost:sum", "name": "rev"}]},
               {"source_model": "cat_rev", "measures": ["rev:avg"]},
           ]),
    _entry("ms_extension_join", "multi_stage",
           [
               {"name": "cust_spend", "source_model": "orders",
                "dimensions": ["customer_id"],
                "measures": [{"formula": "total_cost:sum", "name": "spend"}]},
               {"source_model": {"source_name": "orders",
                                 "joins": [{"target_model": "cust_spend",
                                            "join_pairs": [["customer_id", "customer_id"]]}]},
                "measures": ["*:count", "cust_spend.spend:avg"],
                "time_dimensions": MONTH_TD,
                "order": ASC_TIME},
           ],
           ordered=True, subset_100k=True),
    _entry("ms_dag_parallel", "multi_stage",
           [
               {"name": "cust_spend", "source_model": "orders",
                "dimensions": ["customer_id"],
                "measures": [{"formula": "total_cost:sum", "name": "spend"}]},
               {"name": "tagged_orders",
                "source_model": {"source_name": "orders",
                                 "joins": [{"target_model": "cust_spend",
                                            "join_pairs": [["customer_id", "customer_id"]]}]},
                "dimensions": ["cust_spend.spend"], "measures": ["*:count"]},
               {"source_model": "tagged_orders", "measures": ["_count:max"]},
           ]),
    _entry("ms_out_of_order", "multi_stage",
           [
               {"name": "stage_b", "source_model": "stage_a", "measures": ["*:count"]},
               {"name": "stage_a", "source_model": "orders",
                "measures": ["total_cost:sum"], "time_dimensions": MONTH_TD},
               {"source_model": "stage_b", "measures": ["*:count"]},
           ]),
    _entry("ms_unreachable_stage", "multi_stage",
           [
               {"name": "monthly", "source_model": "orders",
                "measures": ["total_cost:sum"], "time_dimensions": MONTH_TD},
               {"name": "orphan", "source_model": "orders", "measures": ["*:count"]},
               {"source_model": "monthly", "measures": ["*:count"]},
           ]),
    _entry("ms_stage_variable", "multi_stage",
           [
               {"name": "filtered", "source_model": "orders",
                "measures": ["total_cost:sum"], "dimensions": ["category"],
                "filters": ["category = '{cat}'"]},
               {"source_model": "filtered", "measures": ["*:count"]},
           ],
           variables={"cat": "food"}),
    _entry("ms_cycle_error", "multi_stage",
           [
               {"name": "stage_a", "source_model": "stage_b", "measures": ["*:count"]},
               {"name": "stage_b", "source_model": "stage_a", "measures": ["*:count"]},
               {"source_model": "stage_a", "measures": ["*:count"]},
           ],
           expect_error=True),

    # ---- behavior probes ----------------------------------------------------
    _entry("behavior_distinct_dims_default", "behavior",
           _q(dimensions=["category"]),
           oracle={"fn": "agg", "args": {"groupby": ["category"], "aggs": []}}),
    _entry("behavior_distinct_false", "behavior",
           # no oracle: LIMIT without a total order returns an arbitrary subset
           _q(dimensions=["category"], distinct_dimension_values=False, limit=200)),
    _entry("behavior_empty_result", "behavior",
           _q(measures=["total_cost:sum"], dimensions=["category"],
              filters=["total_cost > 99999999"]),
           oracle={"fn": "agg", "args": {"filter": "cost > 99999999",
                                         "groupby": ["category"], "aggs": [SUM_COST]}}),
    _entry("behavior_null_filter_group", "behavior",
           _q(measures=["*:count"], dimensions=["category"], filters=["completed_at IS NULL"]),
           oracle={"fn": "agg", "args": {"filter": "completed_at.isnull()",
                                         "groupby": ["category"], "aggs": [COUNT_STAR]}}),
    _entry("behavior_time_label", "behavior",
           _q(measures=["total_cost:sum"],
              time_dimensions=[{"dimension": "created_at", "granularity": "month",
                                "label": "Order Month"}],
              order=ASC_TIME),
           ordered=True),
    _entry("behavior_function_style_agg", "behavior",
           # normalization advisory expected: function-style agg spelling
           _q(measures=["sum(total_cost)"], dimensions=["category"]),
           oracle={"fn": "agg", "args": {"groupby": ["category"], "aggs": [SUM_COST]}}),
    _entry("behavior_main_time_dimension", "behavior",
           _q(measures=["total_cost:sum",
                        {"formula": "time_shift(total_cost:sum, -1, 'month')", "name": "prev"}],
              main_time_dimension="created_at",
              time_dimensions=MONTH_TD, order=ASC_TIME),
           ordered=True),
    _entry("behavior_limit_zero", "behavior",
           _q(measures=["*:count"], dimensions=["category"], limit=0)),

    # ---- error corpus -------------------------------------------------------
    _entry("err_unknown_column", "errors",
           _q(measures=["nonexistent:sum"]),
           expect_error=True, expect_error_match="nonexistent"),
    _entry("err_unknown_model", "errors",
           {"source_model": "no_such_model", "measures": ["*:count"]},
           expect_error=True, expect_error_match="no_such_model"),
    _entry("err_unknown_agg", "errors",
           _q(measures=["total_cost:sumx"]),
           expect_error=True, expect_error_match="sumx"),
    _entry("err_malformed_formula", "errors",
           _q(measures=[{"formula": "cumsum((", "name": "broken"}]),
           expect_error=True),
    _entry("err_unjoinable_path", "errors",
           _q(measures=["*:count"], dimensions=["regions.name"]),
           expect_error=True, expect_error_match="regions"),
    _entry("err_malformed_filter", "errors",
           _q(measures=["*:count"], filters=["total_cost >"]),
           expect_error=True),
]
