"""DEV-1704 Stage 0 — authoritative main-parity xfail registry.

Every entry is a test that exercises a main-branch feature the typed
pipeline has not yet absorbed. Each is pinned as ``xfail(strict=True)`` via
the ``pytest_collection_modifyitems`` hook in ``tests/conftest.py`` so it
auto-promotes (XPASS -> failure) the moment the owning DEV-1703 stage lands
the feature — DEV-1485 (Stage 11) gates on this dict being empty.

Keyed by exact pytest node id so strict-xfail can never mask a passing test.
"""

PARITY_XFAILS: dict[str, str] = {
    'tests/test_aggregation_gating.py::TestDev1576UnknownVsDisallowed::test_unknown_name_raises_unknown_aggregation': "DEV-1717: DEV-1576 aggregation-gating error-message shape differs on the typed pipeline.",
    'tests/test_aggregation_gating.py::TestDev1576UnknownVsDisallowed::test_unknown_name_lists_known_aggregations': "DEV-1717: DEV-1576 aggregation-gating error-message shape differs on the typed pipeline.",
    'tests/test_aggregation_gating.py::TestDev1576UnknownVsDisallowed::test_unknown_name_suggests_close_match': "DEV-1717: DEV-1576 aggregation-gating error-message shape differs on the typed pipeline.",
    'tests/test_aggregation_gating.py::TestDev1576UnknownVsDisallowed::test_healed_alias_does_not_trigger_unknown': "DEV-1717: DEV-1576 aggregation-gating error-message shape differs on the typed pipeline.",
    'tests/test_aggregation_gating.py::TestDev1576RoundAbsGeneration::test_round_two_args_postgres_casts_to_numeric': "DEV-1717: DEV-1576 aggregation-gating error-message shape differs on the typed pipeline.",
    'tests/test_aggregation_gating.py::TestDev1576UnknownNamePrecedence::test_unknown_name_beats_pk_whitelist_and_type_gates[rating]': "DEV-1717: DEV-1576 aggregation-gating error-message shape differs on the typed pipeline.",
    'tests/test_aggregation_gating.py::TestDev1576UnknownNamePrecedence::test_unknown_name_beats_pk_whitelist_and_type_gates[id]': "DEV-1717: DEV-1576 aggregation-gating error-message shape differs on the typed pipeline.",
    'tests/test_aggregation_gating.py::TestDev1576UnknownNamePrecedence::test_unknown_name_beats_pk_whitelist_and_type_gates[status]': "DEV-1717: DEV-1576 aggregation-gating error-message shape differs on the typed pipeline.",
    'tests/test_aggregation_gating.py::TestDev1576UnknownNamePrecedence::test_known_list_includes_custom_aggregations': "DEV-1717: DEV-1576 aggregation-gating error-message shape differs on the typed pipeline.",
    'tests/test_aggregation_gating.py::TestDev1576CustomAggPrecedence::test_alias_heals_when_no_colliding_custom_agg': "DEV-1717: DEV-1576 aggregation-gating error-message shape differs on the typed pipeline.",
    'tests/test_count_distinct_approx_generation.py::test_duckdb_emits_native_approx': "DEV-1717: count_distinct_approx built-in aggregation not yet on the typed pipeline.",
    'tests/test_count_distinct_approx_generation.py::test_postgres_emits_exact_fallback': "DEV-1717: count_distinct_approx built-in aggregation not yet on the typed pipeline.",
    'tests/test_count_distinct_approx_generation.py::test_clickhouse_routes_to_native_uniq': "DEV-1717: count_distinct_approx built-in aggregation not yet on the typed pipeline.",
    'tests/test_count_distinct_approx_generation.py::test_approx_on_primary_key_column_generates': "DEV-1717: count_distinct_approx built-in aggregation not yet on the typed pipeline.",
    'tests/test_dev1645_invalid_postgres_sql.py::TestFlavorAOrderByUnprojected::test_orderby_nonprojected_column_emits_split_not_composite': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestFlavorAOrderByUnprojected::test_orderby_nonprojected_mixed_case_column_split_and_quoted': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestFlavorAOrderByUnprojected::test_orderby_split_key_keeps_asc_limit_offset': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestFlavorAOrderByUnprojected::test_orderby_unresolvable_joined_column_rejected': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestFlavorAOrderByUnprojected::test_orderby_joined_column_rejected_even_when_filter_pulls_join_in': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestFlavorAOrderByUnprojected::test_orderby_joined_column_rejected_in_cte_wrapped_scope': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestFlavorAOrderByUnprojected::test_orderby_joined_column_rejected_in_first_last_ranked_scope': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestFlavorBMixedCaseQuoting::test_column_sql_mixed_case_quoted': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestFlavorBMixedCaseQuoting::test_filter_predicate_path_mixed_case_quoted': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestFlavorBMixedCaseQuoting::test_model_filter_mixed_case_quoted': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestFlavorBMixedCaseQuoting::test_column_filter_mixed_case_quoted': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestFlavorBMixedCaseQuoting::test_resolved_join_key_mixed_case_quoted': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestFlavorBMixedCaseQuoting::test_bare_mixed_case_dimension_quoted': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestFlavorBMixedCaseQuoting::test_first_last_ranked_mixed_case_dimension_quoted': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestFlavorBMixedCaseQuoting::test_standard_agg_inner_mixed_case_column_quoted': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestFlavorBMixedCaseQuoting::test_resolved_join_target_table_mixed_case_quoted': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestFlavorBMixedCaseQuoting::test_physical_table_name_mixed_case_quoted': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestFlavorBMixedCaseQuoting::test_function_name_not_quoted': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestFlavorBMixedCaseQuoting::test_mixed_case_join_target_alias_consistent': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestMixedCaseHelperUnit::test_quote_mixed_case_identifiers_quotes_uppercase_only': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestMixedCaseHelperUnit::test_quote_mixed_case_idempotent_and_skips_prequoted': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestMixedCaseHelperUnit::test_to_ident_quotes_mixed_case': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestMixedCaseHelperUnit::test_to_table_quotes_physical_name_not_alias': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestMixedCaseQuotingMultiDialect::test_mixed_case_column_quoted_per_dialect[postgres]': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestMixedCaseQuotingMultiDialect::test_mixed_case_column_quoted_per_dialect[sqlite]': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestMixedCaseQuotingMultiDialect::test_mixed_case_column_quoted_per_dialect[duckdb]': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestMixedCaseQuotingMultiDialect::test_mixed_case_column_quoted_per_dialect[snowflake]': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestMixedCaseQuotingMultiDialect::test_mixed_case_column_quoted_per_dialect[mysql]': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestMixedCaseQuotingMultiDialect::test_mixed_case_column_quoted_per_dialect[tsql]': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedAliasQuoting::test_grant_alias_and_qualifier_quoted[postgres]': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedAliasQuoting::test_grant_alias_and_qualifier_quoted[sqlite]': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedAliasQuoting::test_grant_alias_and_qualifier_quoted[duckdb]': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedAliasQuoting::test_grant_alias_and_qualifier_quoted[snowflake]': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedAliasQuoting::test_grant_alias_and_qualifier_quoted[clickhouse]': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedAliasQuoting::test_grant_alias_and_qualifier_quoted[mysql]': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedAliasQuoting::test_grant_alias_and_qualifier_quoted[bigquery]': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedAliasQuoting::test_grant_alias_and_qualifier_quoted[tsql]': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedAliasQuoting::test_other_reserved_model_names[order]': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedAliasQuoting::test_other_reserved_model_names[user]': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedAliasQuoting::test_other_reserved_model_names[group]': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedAliasQuoting::test_other_reserved_model_names[select]': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedAliasQuoting::test_other_reserved_model_names[table]': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedAliasQuoting::test_other_reserved_model_names[between]': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedAliasQuoting::test_mixed_case_reserved_name_consistent': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedStringReparsePaths::test_join_from_reserved_model': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedStringReparsePaths::test_first_last_measure_on_reserved_model': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedStringReparsePaths::test_where_filter_on_reserved_model': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedStringReparsePaths::test_time_shift_with_filter_on_reserved_model': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedStringReparsePaths::test_where_filter_byte_level': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedStringReparsePaths::test_column_level_filter_case_when': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedStringReparsePaths::test_raw_row_distinct_dimension_values_false': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedJoinedFromNonReservedRoot::test_reserved_join_alias_in_projection_and_on': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedJoinedFromNonReservedRoot::test_where_on_reserved_joined_qualifier': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedJoinedFromNonReservedRoot::test_first_last_referencing_reserved_joined': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedInComputedPaths::test_derived_column_referencing_reserved_joined_model': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedInComputedPaths::test_derived_column_reserved_join_discovered_all_dialects[postgres]': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedInComputedPaths::test_derived_column_reserved_join_discovered_all_dialects[mysql]': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedInComputedPaths::test_derived_column_reserved_join_discovered_all_dialects[tsql]': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedInComputedPaths::test_derived_column_reserved_join_discovered_all_dialects[sqlite]': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedInComputedPaths::test_derived_column_reserved_join_discovered_all_dialects[duckdb]': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_filtered_count_forms.py::test_filtered_count_distinct_approx_wraps_case_in_exact_fallback': "DEV-1717: count_distinct_approx built-in aggregation not yet on the typed pipeline.",
    'tests/test_help_seed.py::TestHelpPackageRemoved::test_slayer_help_package_is_deleted': "DEV-1717: DEV-1658 help()->inspect(memory:help.*) migration not adopted; typed pipeline still ships slayer.help.",
    'tests/test_named_measures.py::TestBareNamedMeasureAliasing::test_select_alias_uses_measure_name': "DEV-1713 (Stage 9): bare named-measure SELECT-alias naming.",
    'tests/test_named_measures.py::TestBareNamedMeasureAliasing::test_order_by_resolves_against_measure_name': "DEV-1713 (Stage 9): bare named-measure SELECT-alias naming.",
    'tests/test_mcp_engine_teardown.py::TestToolsReuseClosureEngine::test_recommend_root_model_constructs_no_new_engine': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestResolutionValidation::test_returns_pydantic_result': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestResolutionValidation::test_measure_leaf_accepted': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestResolutionValidation::test_unresolvable_item_raises': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestResolutionValidation::test_bare_model_rejected': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestResolutionValidation::test_bare_datasource_rejected': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestResolutionValidation::test_custom_aggregation_leaf_rejected': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestResolutionValidation::test_cross_datasource_raises': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestResolutionValidation::test_ambiguous_model_without_data_source_raises': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestRootSelection::test_single_model_bare_paths': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestRootSelection::test_fan_out_picks_unmentioned_bridge': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestRootSelection::test_min_hops_prefers_closer_mentioned_root': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestRootSelection::test_multi_hop_diamond_path_lexicographic': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestRootSelection::test_sole_unmentioned_bridge_root': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestRootSelection::test_symmetric_tie_broken_lexicographically': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestAggSuffix::test_simple_suffix_local': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestAggSuffix::test_suffix_cross_model': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestAggSuffix::test_kwarg_suffix_local': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestAggSuffix::test_kwarg_suffix_cross_model_preserved_verbatim': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestAggSuffix::test_dotted_kwarg_arg_preserved_verbatim': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestAggSuffix::test_suffix_through_multi_hop_path': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestInnerJoins::test_inner_pair_routes_from_either_side': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestNoCommonRoot::test_disconnected_returns_structured_no_root': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestNoCommonRoot::test_coverage_surfaces_unmentioned_bridge': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestNoCommonRoot::test_pareto_incomparable_candidates_both_kept': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestNoCommonRoot::test_dominated_candidates_dropped': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestDataSourceAndDedup::test_data_source_disambiguates_same_named_model': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestDataSourceAndDedup::test_already_datasource_qualified_item_passthrough': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestDataSourceAndDedup::test_dotless_item_wrong_data_source_raises': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestDataSourceAndDedup::test_qualified_item_wrong_data_source_raises': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestDataSourceAndDedup::test_dotted_model_colliding_with_datasource_name_scopes_to_model': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestDataSourceAndDedup::test_bare_scope_ignores_aggregation_named_leaf': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestDataSourceAndDedup::test_bare_item_scoped_to_requested_datasource': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestDataSourceAndDedup::test_exact_duplicate_input_deduped': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestDataSourceAndDedup::test_distinct_strings_same_entity_kept_separate': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestSyncWrapper::test_sync_wrapper': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestDistinctOwningModelHopSum::test_hop_total_summed_over_distinct_owning_models': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestRootHint::test_feasible_bridge_hint_honored_over_cheaper_autopick': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestRootHint::test_feasible_hint_equal_to_autopick_honored': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestRootHint::test_bare_and_ds_qualified_hint_equivalent': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestRootHint::test_sync_wrapper_forwards_root_hint': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestRootHint::test_empty_hint_is_noop': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestRootHint::test_whitespace_hint_is_noop': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestRootHint::test_infeasible_hint_falls_back_with_warning': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestRootHint::test_infeasible_warning_echoes_original_ds_qualified_hint': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestRootHint::test_nonexistent_hint_raises': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestRootHint::test_wrong_kind_bare_hint_raises_not_a_model': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestRootHint::test_cross_datasource_hint_raises': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestRootHint::test_three_part_hint_raises': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestRootHint::test_no_root_dominated_hint_row_surfaced': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestRootHint::test_no_root_zero_reach_hint_row_surfaced': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestRootHint::test_no_root_frontier_hint_not_duplicated': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model.py::TestWarningsSurfaced::test_resolver_warnings_are_surfaced': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model_surfaces.py::TestMcpTool::test_markdown_names_root': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model_surfaces.py::TestMcpTool::test_json_format': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model_surfaces.py::TestMcpTool::test_no_root_renders_coverage': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model_surfaces.py::TestMcpTool::test_ambiguous_model_returns_friendly_error': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model_surfaces.py::TestRestEndpoint::test_post_ok': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model_surfaces.py::TestRestEndpoint::test_returns_item_paths': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model_surfaces.py::TestRestEndpoint::test_post_unresolvable_item_400': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model_surfaces.py::TestRestEndpoint::test_post_wrong_kind_400': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model_surfaces.py::TestCliHandler::test_cli_text': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model_surfaces.py::TestCliHandler::test_cli_json': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model_surfaces.py::TestCliParserWiring::test_main_registers_subcommand': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model_surfaces.py::TestSlayerClient::test_local_engine_sync': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model_surfaces.py::TestSlayerClient::test_local_engine_async': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model_surfaces.py::TestRootHintSurfaces::test_mcp_feasible_hint_honored': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model_surfaces.py::TestRootHintSurfaces::test_mcp_bad_hint_friendly_error': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model_surfaces.py::TestRootHintSurfaces::test_rest_feasible_hint_honored': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model_surfaces.py::TestRootHintSurfaces::test_rest_bad_hint_400': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model_surfaces.py::TestRootHintSurfaces::test_cli_feasible_hint_honored': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model_surfaces.py::TestRootHintSurfaces::test_cli_parser_accepts_root_hint': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model_surfaces.py::TestRootHintSurfaces::test_client_local_feasible_hint_honored': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_recommend_root_model_surfaces.py::TestRootHintSurfaces::test_client_local_bad_hint_raises': "DEV-1717: DEV-1626 recommend_root_model engine method not yet on the typed pipeline.",
    'tests/test_sql_generator.py::TestFields::test_multiple_time_shifts_in_arithmetic_unique_ctes': "DEV-1713 (Stage 9): DEV-1692 duplicate time_shift CTE de-collision.",
    'tests/test_sql_generator.py::TestFilterOuterParenWrapDev1539::test_filter_inlines_multiterm_local_column_with_outer_parens': "DEV-1706 (Stage 2): DEV-1539 predicate outer-parens (resolver invariant).",
    'tests/test_sql_generator.py::TestFilterOuterParenWrapDev1539::test_dsl_compare_lhs_binop_wrapped': "DEV-1706 (Stage 2): DEV-1539 predicate outer-parens (resolver invariant).",
    'tests/test_sql_generator.py::TestFilterOuterParenWrapDev1539::test_dsl_compare_rhs_binop_wrapped': "DEV-1706 (Stage 2): DEV-1539 predicate outer-parens (resolver invariant).",
    'tests/test_sql_generator.py::TestFilterOuterParenWrapDev1539::test_dsl_compare_lhs_boolop_wrapped': "DEV-1706 (Stage 2): DEV-1539 predicate outer-parens (resolver invariant).",
    'tests/test_sql_generator.py::TestFilterOuterParenWrapDev1539::test_dsl_compare_rhs_boolop_wrapped': "DEV-1706 (Stage 2): DEV-1539 predicate outer-parens (resolver invariant).",
    'tests/test_sql_generator.py::TestFilterOuterParenWrapDev1539::test_having_multiterm_measure_wrapped': "DEV-1706 (Stage 2): DEV-1539 predicate outer-parens (resolver invariant).",
    'tests/test_sql_generator.py::TestFilterOuterParenWrapDev1539::test_filter_inlines_and_or_connector_column_with_outer_parens[archived AND deleted-AND]': "DEV-1706 (Stage 2): DEV-1539 predicate outer-parens (resolver invariant).",
    'tests/test_sql_generator.py::TestFilterOuterParenWrapDev1539::test_filter_inlines_and_or_connector_column_with_outer_parens[archived OR deleted-OR]': "DEV-1706 (Stage 2): DEV-1539 predicate outer-parens (resolver invariant).",
    'tests/test_sql_generator.py::TestFilterOuterParenWrapDev1539::test_filter_inlines_not_predicate_column_with_outer_parens': "DEV-1706 (Stage 2): DEV-1539 predicate outer-parens (resolver invariant).",
    'tests/test_sql_generator.py::TestFilterOuterParenWrapDev1539::test_filter_inlines_between_predicate_column_with_outer_parens': "DEV-1706 (Stage 2): DEV-1539 predicate outer-parens (resolver invariant).",
    'tests/test_sql_generator.py::TestFilterOuterParenWrapDev1539::test_filter_inlines_in_predicate_column_with_outer_parens': "DEV-1706 (Stage 2): DEV-1539 predicate outer-parens (resolver invariant).",
}
