"""DEV-1704 Stage 0 — authoritative main-parity xfail registry.

Every entry is a test that exercises a main-branch feature the typed
pipeline has not yet absorbed. Each is pinned as ``xfail(strict=True)`` via
the ``pytest_collection_modifyitems`` hook in ``tests/conftest.py`` so it
auto-promotes (XPASS -> failure) the moment the owning DEV-1703 stage lands
the feature — DEV-1485 (Stage 11) gates on this dict being empty.

Keyed by exact pytest node id so strict-xfail can never mask a passing test.
"""

PARITY_XFAILS: dict[str, str] = {
    'tests/test_dev1645_invalid_postgres_sql.py::TestFlavorAOrderByUnprojected::test_orderby_nonprojected_column_emits_split_not_composite': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestFlavorAOrderByUnprojected::test_orderby_nonprojected_mixed_case_column_split_and_quoted': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestFlavorAOrderByUnprojected::test_orderby_split_key_keeps_asc_limit_offset': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestFlavorAOrderByUnprojected::test_orderby_unresolvable_joined_column_rejected': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestFlavorAOrderByUnprojected::test_orderby_joined_column_rejected_even_when_filter_pulls_join_in': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestFlavorAOrderByUnprojected::test_orderby_joined_column_rejected_in_cte_wrapped_scope': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestFlavorAOrderByUnprojected::test_orderby_joined_column_rejected_in_first_last_ranked_scope': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestFlavorBMixedCaseQuoting::test_column_sql_mixed_case_quoted': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestFlavorBMixedCaseQuoting::test_filter_predicate_path_mixed_case_quoted': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestFlavorBMixedCaseQuoting::test_model_filter_mixed_case_quoted': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestFlavorBMixedCaseQuoting::test_column_filter_mixed_case_quoted': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestFlavorBMixedCaseQuoting::test_resolved_join_key_mixed_case_quoted': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestFlavorBMixedCaseQuoting::test_bare_mixed_case_dimension_quoted': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestFlavorBMixedCaseQuoting::test_first_last_ranked_mixed_case_dimension_quoted': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestFlavorBMixedCaseQuoting::test_standard_agg_inner_mixed_case_column_quoted': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestFlavorBMixedCaseQuoting::test_resolved_join_target_table_mixed_case_quoted': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestFlavorBMixedCaseQuoting::test_physical_table_name_mixed_case_quoted': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestFlavorBMixedCaseQuoting::test_function_name_not_quoted': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestFlavorBMixedCaseQuoting::test_mixed_case_join_target_alias_consistent': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestMixedCaseHelperUnit::test_quote_mixed_case_identifiers_quotes_uppercase_only': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestMixedCaseHelperUnit::test_quote_mixed_case_idempotent_and_skips_prequoted': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestMixedCaseHelperUnit::test_to_ident_quotes_mixed_case': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestMixedCaseHelperUnit::test_to_table_quotes_physical_name_not_alias': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestMixedCaseQuotingMultiDialect::test_mixed_case_column_quoted_per_dialect[postgres]': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestMixedCaseQuotingMultiDialect::test_mixed_case_column_quoted_per_dialect[sqlite]': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestMixedCaseQuotingMultiDialect::test_mixed_case_column_quoted_per_dialect[duckdb]': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestMixedCaseQuotingMultiDialect::test_mixed_case_column_quoted_per_dialect[snowflake]': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestMixedCaseQuotingMultiDialect::test_mixed_case_column_quoted_per_dialect[mysql]': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1645_invalid_postgres_sql.py::TestMixedCaseQuotingMultiDialect::test_mixed_case_column_quoted_per_dialect[tsql]': "DEV-1712 (Stage 8): DEV-1645 ORDER BY policies (unprojected/joined sort keys).",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedAliasQuoting::test_grant_alias_and_qualifier_quoted[postgres]': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedAliasQuoting::test_grant_alias_and_qualifier_quoted[sqlite]': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedAliasQuoting::test_grant_alias_and_qualifier_quoted[duckdb]': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedAliasQuoting::test_grant_alias_and_qualifier_quoted[snowflake]': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedAliasQuoting::test_grant_alias_and_qualifier_quoted[clickhouse]': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedAliasQuoting::test_grant_alias_and_qualifier_quoted[mysql]': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedAliasQuoting::test_grant_alias_and_qualifier_quoted[bigquery]': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedAliasQuoting::test_grant_alias_and_qualifier_quoted[tsql]': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedAliasQuoting::test_other_reserved_model_names[order]': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedAliasQuoting::test_other_reserved_model_names[user]': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedAliasQuoting::test_other_reserved_model_names[group]': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedAliasQuoting::test_other_reserved_model_names[select]': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedAliasQuoting::test_other_reserved_model_names[table]': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedAliasQuoting::test_other_reserved_model_names[between]': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedAliasQuoting::test_mixed_case_reserved_name_consistent': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedStringReparsePaths::test_join_from_reserved_model': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedStringReparsePaths::test_first_last_measure_on_reserved_model': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedStringReparsePaths::test_where_filter_on_reserved_model': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedStringReparsePaths::test_time_shift_with_filter_on_reserved_model': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedStringReparsePaths::test_where_filter_byte_level': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedStringReparsePaths::test_column_level_filter_case_when': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedStringReparsePaths::test_raw_row_distinct_dimension_values_false': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedJoinedFromNonReservedRoot::test_reserved_join_alias_in_projection_and_on': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedJoinedFromNonReservedRoot::test_where_on_reserved_joined_qualifier': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedJoinedFromNonReservedRoot::test_first_last_referencing_reserved_joined': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedInComputedPaths::test_derived_column_referencing_reserved_joined_model': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedInComputedPaths::test_derived_column_reserved_join_discovered_all_dialects[postgres]': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedInComputedPaths::test_derived_column_reserved_join_discovered_all_dialects[mysql]': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedInComputedPaths::test_derived_column_reserved_join_discovered_all_dialects[tsql]': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedInComputedPaths::test_derived_column_reserved_join_discovered_all_dialects[sqlite]': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_dev1686_reserved_word_identifiers.py::TestReservedInComputedPaths::test_derived_column_reserved_join_discovered_all_dialects[duckdb]': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting via the resolver/dialect package.",
    'tests/test_named_measures.py::TestBareNamedMeasureAliasing::test_select_alias_uses_measure_name': "DEV-1713 (Stage 9): bare named-measure SELECT-alias naming.",
    'tests/test_named_measures.py::TestBareNamedMeasureAliasing::test_order_by_resolves_against_measure_name': "DEV-1713 (Stage 9): bare named-measure SELECT-alias naming.",
    'tests/test_sql_generator.py::TestFields::test_multiple_time_shifts_in_arithmetic_unique_ctes': "DEV-1713 (Stage 9): DEV-1692 duplicate time_shift CTE de-collision.",
    'tests/test_sql_generator.py::TestFilterOuterParenWrapDev1539::test_filter_inlines_multiterm_local_column_with_outer_parens': "DEV-1706 (Stage 2): DEV-1539 predicate outer-parens (resolver invariant).",
    'tests/test_sql_generator.py::TestFilterOuterParenWrapDev1539::test_dsl_compare_lhs_binop_wrapped': "DEV-1706 (Stage 2): DEV-1539 predicate outer-parens (resolver invariant).",
    'tests/test_sql_generator.py::TestFilterOuterParenWrapDev1539::test_dsl_compare_rhs_binop_wrapped': "DEV-1706 (Stage 2): DEV-1539 predicate outer-parens (resolver invariant).",
    'tests/test_sql_generator.py::TestFilterOuterParenWrapDev1539::test_dsl_compare_lhs_boolop_wrapped': "DEV-1706 (Stage 2): DEV-1539 predicate outer-parens (resolver invariant).",
    'tests/test_sql_generator.py::TestFilterOuterParenWrapDev1539::test_dsl_compare_rhs_boolop_wrapped': "DEV-1706 (Stage 2): DEV-1539 predicate outer-parens (resolver invariant).",
    'tests/test_sql_generator.py::TestFilterOuterParenWrapDev1539::test_having_multiterm_measure_wrapped': "DEV-1706 (Stage 2): DEV-1539 predicate outer-parens (resolver invariant).",
    'tests/test_sql_generator.py::TestFilterOuterParenWrapDev1539::test_filter_inlines_and_or_connector_column_with_outer_parens[archived AND deleted-AND]': "DEV-1706 (Stage 2): DEV-1539 predicate outer-parens (resolver invariant).",
    'tests/test_sql_generator.py::TestFilterOuterParenWrapDev1539::test_filter_inlines_and_or_connector_column_with_outer_parens[archived OR deleted-OR]': "DEV-1706 (Stage 2): DEV-1539 predicate outer-parens (resolver invariant).",
    'tests/test_sql_generator.py::TestFilterOuterParenWrapDev1539::test_filter_inlines_not_predicate_column_with_outer_parens': "DEV-1706 (Stage 2): DEV-1539 predicate outer-parens (resolver invariant).",
    'tests/test_sql_generator.py::TestFilterOuterParenWrapDev1539::test_filter_inlines_between_predicate_column_with_outer_parens': "DEV-1706 (Stage 2): DEV-1539 predicate outer-parens (resolver invariant).",
    'tests/test_sql_generator.py::TestFilterOuterParenWrapDev1539::test_filter_inlines_in_predicate_column_with_outer_parens': "DEV-1706 (Stage 2): DEV-1539 predicate outer-parens (resolver invariant).",
    'tests/integration/test_integration.py::test_multiple_time_shifts_in_one_query': "DEV-1713 (Stage 9): DEV-1692 duplicate time_shift CTE de-collision.",
    'tests/integration/test_integration.py::test_dev1539_where_multiterm_filter_emits_outer_parens': "DEV-1706 (Stage 2): DEV-1539 predicate outer-parens (resolver invariant).",
    'tests/integration/test_integration.py::test_dev1539_having_multiterm_measure_emits_outer_parens': "DEV-1706 (Stage 2): DEV-1539 predicate outer-parens (resolver invariant).",
    'tests/integration/test_integration_postgres.py::TestDev1645ValidPostgres::test_flavor_b_mixed_case_column_sql_executes': "DEV-1712 (Stage 8): DEV-1645 ORDER BY / mixed-case identifier policies.",
    'tests/integration/test_integration_postgres.py::TestDev1645ValidPostgres::test_flavor_b_mixed_case_join_key_executes': "DEV-1712 (Stage 8): DEV-1645 ORDER BY / mixed-case identifier policies.",
    'tests/integration/test_integration_postgres.py::TestDev1645ValidPostgres::test_flavor_a_orderby_nonprojected_column_executes': "DEV-1712 (Stage 8): DEV-1645 ORDER BY unprojected column policy.",
    'tests/integration/test_integration_postgres.py::TestPostgresReservedWordModel::test_standalone_grant_dims_count_executes': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting.",
    'tests/integration/test_integration_postgres.py::TestPostgresReservedWordModel::test_join_from_grant_executes': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting.",
    'tests/integration/test_integration_postgres.py::TestPostgresReservedWordModel::test_grant_measure_and_filter_executes': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting.",
    'tests/integration/test_integration_postgres.py::TestPostgresReservedWordModel::test_query_backed_model_with_reserved_short_executes': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting.",
    'tests/integration/test_integration_postgres.py::TestPostgresReservedWordModel::test_derived_column_referencing_reserved_join_executes': "DEV-1706 (Stage 2): DEV-1686 reserved-identifier quoting.",
}
