version: 7
name: products
sql_table: products
query_variables: {}
data_source: jaffle_shop
columns:
- name: sku
  sql: sku
  type: TEXT
  primary_key: true
  description: Product identifier.
  label: SKU
  hidden: false
- name: name
  sql: name
  type: TEXT
  primary_key: false
  description: Product name.
  label: Product
  hidden: false
- name: type
  sql: type
  type: TEXT
  primary_key: false
  description: Product category (jaffle or beverage).
  label: Category
  hidden: false
- name: price
  sql: price
  type: DOUBLE
  primary_key: false
  description: List price, in dollars.
  label: Price
  hidden: false
  format:
    type: currency
    precision: 2
    symbol: $
- name: description
  sql: description
  type: TEXT
  primary_key: false
  description: Product description.
  label: Description
  hidden: false
measures:
- formula: sku:count_distinct
  name: product_count
  label: Products
  description: Number of distinct products.
  type: INT
- formula: price:avg
  name: avg_price
  label: Average Price
  description: Average list price, in dollars.
  type: DOUBLE
aggregations: []
joins: []
filters: []
description: "Menu items sold at the Jaffle Shop \u2014 jaffles and beverages."
hidden: false
